name: Publish package to github npm registry

on: 
    push:
        - main
  release:
    types: published
    
    
jobs:
    test-publish-package:
        name: publish package
        permissions:
            packages:
                write
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
            registry-url: https://npm.pkg.github.com
        - name: Install dependenices
          run: npm install

        - name: Publish to npm Github registry
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}